<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\Repositories\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.EntityFrameworkCore">
        <HintPath>..\..\..\.nuget\packages\microsoft.entityframeworkcore\10.0.3\lib\net10.0\Microsoft.EntityFrameworkCore.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DistributedExecutionEngine.Domain\DistributedExecutionEngine.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    </ItemGroup>

</Project>
